apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-backend
  template:
    metadata:
      labels:
        app: url-shortener-backend
    spec:
      containers:
        - name: backend
          image: url-shortener-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: MONGO_URI
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: REDIS_PORT
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: FRONTEND_URL
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: BASE_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend
spec:
  selector:
    app: url-shortener-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30002
  type: NodePort
